sudo: false

language: node_js

node_js:
  - "8"

notifications:
  disabled: true

before_install:
  - npm install -g npm@5

install:
  - npm install -g typescript
  - npm install -g codecov
  - npm install
  - npm run build

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

script:
  - npm test
  - codecov
